service:
  name: monitor

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    excludeFiles: src/**/*.test.ts

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-glob-merge-yaml

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 5
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  tracing:
    lambda: true
    apiGateway: true
  iamRoleStatements:
    ${glob-merge-yaml:src/**/serverless.yml:provider.iamRoleStatements}
  environment:
    ${glob-merge-yaml:src/**/serverless.yml:provider.environment}

functions:
  ${glob-merge-yaml:src/**/serverless.yml:functions}

resources:
  ${glob-merge-yaml:src/**/serverless.yml:resources}
